### ISSUE TITLE
Enable the IBM App ID Authentication

### ISSUE THREAD

**Issue by amfred** [Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator#11]
We need to complete the internal onboarding process for an App ID.
Then set up the JWT to be used for authentication.

**Comment by yochanah** [comment]
Duplicate Issue : https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/22

**Comment by amfred** [comment]
I think you're right @yochanah

**Comment by upkarlidder** [comment]
Closing. Duplicate of https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/22.
