### ISSUE TITLE
Change the "master" branch to "main"

### ISSUE THREAD

**Issue by amfred** [Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator#12]

**Comment by amfred** [comment]
Note from @johnwalicki 

For Open-Sentencing-* repos that have completely merged branches, its easy to rename master to main
As of 12-08-20, I see that I can rename the top level and aggregrator repos but the UI and Model repos have open branches. Renaming master to main before those PRs are merged will cause some merge confusion.

I'll rename the first two and work with the teams on the others.

**Comment by amfred** [comment]
Still important...

**Comment by upkarlidder** [comment]
Looks like all branches have been moved to `main`. Do we need to reopen this @amfred?

**Comment by demilolu** [comment]
is this done?

**Comment by johnwalicki** [comment]
Yes, it's done.
