### ISSUE TITLE
Shift Aggregator to be java class based 

### ISSUE THREAD

**Issue by demilolu** [Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator#31]
### Background on the problem the feature will solve/improved user experience
Currently our aggregator is Swagger based, which might be fast in the short term but limiting long term. 

### Describe the solution you'd like
Shift to class-based view in aggregator
 
### Tasks 
Description of the development tasks needed to complete this issue, including tests, 

### Acceptance Criteria 
Standards we believe this issue must reach to be considered complete and ready for a pull request. E.g precisely all  the user should be able to do with this update, performance requirements, security requirements, etc as appropriate.

**Comment by upkarlidder** [comment]
Closing. Duplicate of https://github.com/Call-for-Code-for-Racial-Justice/Open-Sentencing-Aggregator/issues/25
